CREATE TABLE users (id INT, username TEXT);
INSERT INTO users VALUES (1, 'Alice');
INSERT INTO users VALUES (2, 'Bob');
INSERT INTO users VALUES (3, 'Charlie');
INSERT INTO users VALUES (4, 'Dave');
INSERT INTO users VALUES (5, 'Eve');
INSERT INTO users VALUES (6, 'Frank');
INSERT INTO users VALUES (7, 'Grace');
INSERT INTO users VALUES (8, 'Heidi');
INSERT INTO users VALUES (9, 'Ivan');
INSERT INTO users VALUES (10, 'Judy');
INSERT INTO users VALUES (11, 'Kevin');
INSERT INTO users VALUES (12, 'Laura');
INSERT INTO users VALUES (13, 'Mallory');
INSERT INTO users VALUES (14, 'Niaj');
INSERT INTO users VALUES (15, 'Oscar');
INSERT INTO users VALUES (16, 'Peggy');
INSERT INTO users VALUES (17, 'Quentin');
INSERT INTO users VALUES (18, 'Rose');
INSERT INTO users VALUES (19, 'Sybil');
INSERT INTO users VALUES (20, 'Trent');
INSERT INTO users VALUES (21, 'Ursula');
INSERT INTO users VALUES (22, 'Victor');
INSERT INTO users VALUES (23, 'Walter');
INSERT INTO users VALUES (24, 'Xenia');
INSERT INTO users VALUES (25, 'Yvonne');
INSERT INTO users VALUES (26, 'Zoe');
SELECT * FROM users;
.exit
